
import { Part, Fleet, ShipData } from './types';

export const MAX_GRID_EXTENT = 15;

export const AVAILABLE_PARTS: Part[] = [
  {
    id: 'bridge-classic',
    type: 'COCKPIT',
    name: 'Command Bridge',
    size: [2, 1, 2],
    cost: 55000,
    mass: 140,
    powerDraw: 18,
    powerGen: 0,
    crewCapacity: 5,
    integrity: 600,
    armorValue: 60,
    platingThickness: 6,
    icon: 'fa-solid fa-microchip',
    color: '#00f2ff',
  },
  {
    id: 'bridge-scout',
    type: 'COCKPIT',
    name: 'Scout Cockpit',
    size: [1, 1, 1],
    cost: 25000,
    mass: 60,
    powerDraw: 10,
    powerGen: 0,
    crewCapacity: 1,
    integrity: 300,
    armorValue: 20,
    platingThickness: 3,
    icon: 'fa-solid fa-eye',
    color: '#00ccff',
  },
  {
    id: 'engine-fusion',
    type: 'ENGINE',
    name: 'Fusion Thruster',
    size: [1, 1, 2],
    cost: 40000,
    mass: 220,
    powerDraw: 45,
    powerGen: 0,
    crewCapacity: 0,
    integrity: 350,
    armorValue: 30,
    platingThickness: 10,
    icon: 'fa-solid fa-shuttle-space',
    color: '#ff0055',
  },
  {
    id: 'engine-ion',
    type: 'ENGINE',
    name: 'Ion Pulse Drive',
    size: [1, 1, 1],
    cost: 15000,
    mass: 90,
    powerDraw: 15,
    powerGen: 0,
    crewCapacity: 0,
    integrity: 150,
    armorValue: 10,
    platingThickness: 2,
    icon: 'fa-solid fa-bolt',
    color: '#3399ff',
  },
  {
    id: 'reactor-plasma',
    type: 'REACTOR',
    name: 'Plasma Core',
    size: [1, 1, 1],
    cost: 45000,
    mass: 150,
    powerDraw: 0,
    powerGen: 150,
    crewCapacity: 0,
    integrity: 200,
    armorValue: 20,
    platingThickness: 12,
    icon: 'fa-solid fa-atom',
    color: '#39ff14',
  },
  {
    id: 'reactor-antimatter',
    type: 'REACTOR',
    name: 'AM Containment',
    size: [2, 2, 2],
    cost: 120000,
    mass: 600,
    powerDraw: 0,
    powerGen: 800,
    crewCapacity: 0,
    integrity: 400,
    armorValue: 100,
    platingThickness: 20,
    icon: 'fa-solid fa-radiation',
    color: '#a855f7',
  },
  {
    id: 'quarters-std',
    type: 'QUARTERS',
    name: 'Crew Bunks',
    size: [1, 1, 1],
    cost: 6000,
    mass: 50,
    powerDraw: 5,
    powerGen: 0,
    crewCapacity: 8,
    integrity: 200,
    armorValue: 10,
    platingThickness: 3,
    icon: 'fa-solid fa-bed',
    color: '#ffaa00',
  },
  {
    id: 'med-bay',
    type: 'QUARTERS',
    name: 'Medical Suite',
    size: [1, 1, 1],
    cost: 22000,
    mass: 70,
    powerDraw: 15,
    powerGen: 0,
    crewCapacity: 4,
    integrity: 300,
    armorValue: 15,
    platingThickness: 5,
    icon: 'fa-solid fa-house-medical',
    color: '#f87171',
  },
  {
    id: 'cargo-bay',
    type: 'CARGO',
    name: 'Large Cargo Bay',
    size: [2, 1, 2],
    cost: 14000,
    mass: 100,
    powerDraw: 3,
    powerGen: 0,
    crewCapacity: 0,
    integrity: 300,
    armorValue: 20,
    platingThickness: 4,
    icon: 'fa-solid fa-boxes-stacked',
    color: '#94a3b8',
  },
  {
    id: 'weapon-laser',
    type: 'WEAPON',
    name: 'Pulse Cannon',
    size: [1, 1, 1],
    cost: 30000,
    mass: 45,
    powerDraw: 25,
    powerGen: 0,
    crewCapacity: 0,
    integrity: 120,
    armorValue: 45,
    platingThickness: 7,
    icon: 'fa-solid fa-crosshairs',
    color: '#ff3300',
  },
  {
    id: 'weapon-railgun',
    type: 'WEAPON',
    name: 'Kinetic Railgun',
    size: [1, 1, 3],
    cost: 65000,
    mass: 300,
    powerDraw: 60,
    powerGen: 0,
    crewCapacity: 0,
    integrity: 400,
    armorValue: 80,
    platingThickness: 15,
    icon: 'fa-solid fa-gun',
    color: '#fb923c',
  },
  {
    id: 'shield-gen',
    type: 'HULL',
    name: 'Aegis Shield',
    size: [1, 1, 1],
    cost: 48000,
    mass: 120,
    powerDraw: 50,
    powerGen: 0,
    crewCapacity: 0,
    integrity: 1500,
    armorValue: 300,
    platingThickness: 0,
    icon: 'fa-solid fa-shield-halved',
    color: '#3b82f6',
  },
  {
    id: 'hull-heavy',
    type: 'HULL',
    name: 'Heavy Plate',
    size: [1, 1, 1],
    cost: 4500,
    mass: 250,
    powerDraw: 0,
    powerGen: 0,
    crewCapacity: 0,
    integrity: 1200,
    armorValue: 200,
    platingThickness: 25,
    icon: 'fa-solid fa-square',
    color: '#475569',
  },
  {
    id: 'sensor-dish',
    type: 'COMM',
    name: 'Comms Uplink',
    size: [1, 1, 1],
    cost: 18000,
    mass: 35,
    powerDraw: 12,
    powerGen: 0,
    crewCapacity: 0,
    integrity: 60,
    armorValue: 5,
    platingThickness: 2,
    icon: 'fa-solid fa-satellite-dish',
    color: '#d946ef',
  }
];

// Demo ships helper
const createDemoShip = (name: string, partConfigs: {id: string, pos: [number, number, number], rot?: number}[]): ShipData => ({
  id: crypto.randomUUID(),
  name,
  parts: partConfigs.map(c => {
    const p = AVAILABLE_PARTS.find(ap => ap.id === c.id)!;
    return { ...p, instanceId: crypto.randomUUID(), position: c.pos, rotation: c.rot || 0 };
  }),
  hullVisuals: null,
  conceptImageUrl: null,
  videoUrl: null,
  analysis: null,
  createdAt: Date.now()
});

export const DEMO_FLEET: Fleet = {
  id: 'nexus-prime-001',
  name: 'Nexus Prime Command',
  isLocked: true,
  ships: [
    createDemoShip('Stinger Scout', [
      { id: 'bridge-scout', pos: [0, 0, 1] },
      { id: 'reactor-plasma', pos: [0, 0, 0] },
      { id: 'engine-ion', pos: [0, 0, -1] }
    ]),
    createDemoShip('Vanguard Interceptor', [
      { id: 'bridge-classic', pos: [0, 0, 1.5] },
      { id: 'reactor-plasma', pos: [0, 0, 0.5] },
      { id: 'hull-heavy', pos: [0, 0, -0.5] },
      { id: 'engine-fusion', pos: [1, 0, -1] },
      { id: 'engine-fusion', pos: [-1, 0, -1] },
      { id: 'weapon-laser', pos: [1, 0, 0.5] },
      { id: 'weapon-laser', pos: [-1, 0, 0.5] }
    ]),
    createDemoShip('Atlas Bulk-Carrier', [
      { id: 'bridge-classic', pos: [0, 1, 2] },
      { id: 'cargo-bay', pos: [0, 0, 0.5] },
      { id: 'cargo-bay', pos: [0, 0, -1.5] },
      { id: 'reactor-antimatter', pos: [0, -1, -0.5] },
      { id: 'engine-fusion', pos: [1.5, -1, -2] },
      { id: 'engine-fusion', pos: [-1.5, -1, -2] },
      { id: 'hull-heavy', pos: [2, 0, 0] },
      { id: 'hull-heavy', pos: [-2, 0, 0] }
    ]),
    createDemoShip('Odyssey Long-Range', [
      { id: 'bridge-classic', pos: [0, 0, 2] },
      { id: 'quarters-std', pos: [1, 0, 1] },
      { id: 'quarters-std', pos: [-1, 0, 1] },
      { id: 'med-bay', pos: [0, 1, 1] },
      { id: 'reactor-plasma', pos: [0, 0, 0] },
      { id: 'sensor-dish', pos: [0, 1, 0] },
      { id: 'engine-ion', pos: [0, 0, -1] },
      { id: 'shield-gen', pos: [0, -1, 0] }
    ]),
    createDemoShip('Behemoth Destroyer', [
      { id: 'bridge-classic', pos: [0, 2, 0] },
      { id: 'reactor-antimatter', pos: [0, 0, 0] },
      { id: 'hull-heavy', pos: [0, 1, 0] },
      { id: 'hull-heavy', pos: [1, 0, 0] },
      { id: 'hull-heavy', pos: [-1, 0, 0] },
      { id: 'hull-heavy', pos: [0, -1, 0] },
      { id: 'weapon-railgun', pos: [0, 0, 2] },
      { id: 'weapon-railgun', pos: [1, 1, 1] },
      { id: 'weapon-railgun', pos: [-1, 1, 1] },
      { id: 'engine-fusion', pos: [0, 0, -2] },
      { id: 'shield-gen', pos: [1.5, 0, 0] },
      { id: 'shield-gen', pos: [-1.5, 0, 0] }
    ]),
    createDemoShip('Nebula Research', [
      { id: 'bridge-scout', pos: [0, 0.5, 1] },
      { id: 'reactor-plasma', pos: [0, 0, 0] },
      { id: 'sensor-dish', pos: [0, 1, -1], rot: 180 },
      { id: 'quarters-std', pos: [0, -1, 0] },
      { id: 'med-bay', pos: [0, 1, 0] },
      { id: 'engine-ion', pos: [0, 0, -1.5] }
    ])
  ]
};
